# .github/workflows/update-readme.yml
name: Atualizar README mensalmente

on:
  schedule:
    - cron: '0 0 1 * *'  # todo dia 1 do mês à meia-noite UTC
  workflow_dispatch:      # também pode rodar manualmente

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-cool/github-profile-readme-action@v2
